services:
  frontend:
    container_name: oasis-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - REACT_APP_ENVIRONMENT=dev
      - REACT_APP_API=https://oasis-backend.esup-portail.org
      - REACT_APP_FRONTEND=https://oasis.esup-portail.org
      - REACT_APP_OAUTH_CLIENT_ID=oasis
      - REACT_APP_OAUTH_PROVIDER=https://cas.esup-portail.org/cas/oauth2.0/authorize