services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'

  App\Tests\Behat\FixturesLoaderTrait:
    arguments:
      - '@fidry_alice_data_fixtures.doctrine.persister_loader'

  App\Tests\Behat\ReferentielContext:
    arguments:
      - '@fidry_alice_data_fixtures.doctrine.persister_loader'
      - '@doctrine'
      - '%kernel.project_dir%/fixtures/tests'