###############################################################################
#                             Planiphase-back                                 #
###############################################################################
version: "3.1"
services:
  http:
    container_name: http
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_VERSION=${APP_VERSION}
      - APP_DEBUG=${APP_DEBUG}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - OAUTH_CLIENTID=${OAUTH_CLIENTID}
      - OAUTH_CLIENTSECRET=${OAUTH_CLIENTSECRET}
      - OAUTH_REDIRECTURI=${OAUTH_REDIRECTURI}
      - OAUTH_URLAUTHORIZE=${OAUTH_URLAUTHORIZE}
      - OAUTH_URLACCESSTOKEN=${OAUTH_URLACCESSTOKEN}
      - OAUTH_URLRESOURCEOWNERDETAILS=${OAUTH_URLRESOURCEOWNERDETAILS}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_SSL=${LDAP_SSL}
      - LDAP_USERNAME=${LDAP_USERNAME}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_DN=${LDAP_DN}
      - APOGEE_USER=${APOGEE_USER}
      - APOGEE_PWD=${APOGEE_PWD}
      - APOGEE_DB=${APOGEE_DB}
      - MAILER_DSN=${MAILER_DSN}
  messenger-worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./Dockerfile-worker
    environment:
      - APP_ENV=${APP_ENV}
      - APP_VERSION=${APP_VERSION}
      - APP_DEBUG=${APP_DEBUG}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - OAUTH_CLIENTID=${OAUTH_CLIENTID}
      - OAUTH_CLIENTSECRET=${OAUTH_CLIENTSECRET}
      - OAUTH_REDIRECTURI=${OAUTH_REDIRECTURI}
      - OAUTH_URLAUTHORIZE=${OAUTH_URLAUTHORIZE}
      - OAUTH_URLACCESSTOKEN=${OAUTH_URLACCESSTOKEN}
      - OAUTH_URLRESOURCEOWNERDETAILS=${OAUTH_URLRESOURCEOWNERDETAILS}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_SSL=${LDAP_SSL}
      - LDAP_USERNAME=${LDAP_USERNAME}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_DN=${LDAP_DN}
      - APOGEE_USER=${APOGEE_USER}
      - APOGEE_PWD=${APOGEE_PWD}
      - APOGEE_DB=${APOGEE_DB}
      - MAILER_DSN=${MAILER_DSN}