lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: '%env(JWT_TOKEN_TTL)%'

  # token extraction settings
  token_extractors:
    # check token in request
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
    # check token in a cookie (prévenir si modification du nom)
    cookie:
      enabled: true
      name: '%env(JWT_COOKIE_NAME)%'